# Generated by Django 4.1.7 on 2023-02-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=50)),
                ('conform_password', models.CharField(max_length=50)),
            ],
        ),
    ]
